export interface MouvementStock {
  id: string; // minuscule
  magasinID: number;
  magasinNom: string;
  campagneID: string;
  exportateurID?: number | null;
  exportateurNom?: string | null;
  mouvementTypeID: number;
  mouvementTypeDesignation: string;
  certificationID?: number | null;
  certificationDesignation?: string | null;
  sacTypeID?: number | null;
  sacTypeDesignation?: string | null;
  objetEnStockID?: string | null;
  objetEnStockType?: number | null;
  emplacementID?: number | null;
  emplacementDesignation?: string | null;
  siteID: number;
  siteNom: string;
  reference1?: string | null;
  reference2?: string | null;
  reference3?: string | null;
  dateMouvement: string;
  sens: number;
  quantite: number;
  poidsBrut: number;
  tareSacs: number;
  tarePalettes: number;
  poidsNetLivre: number;
  retentionPoids: number;
  poidsNetAccepte: number;
  statut?: string | null;
  commentaire?: string | null;
  desactive?: boolean | null;
  approbationUtilisateur?: string | null;
  approbationDate?: string | null;
  creationUtilisateur: string;
  creationDate: string;
  modificationUtilisateur?: string | null;
  modificationDate?: string | null;
  rowVersionKey?: any | null;
  produitID?: number | null;
}