import { MouvementStock } from '../type';

export const mockMouvements: MouvementStock[] = [
  {
    id: '1',
    magasinID: 1,
    magasinNom: 'Magasin A',
    campagneID: '2023',
    exportateurID: 101,
    exportateurNom: 'Exportateur X',
    mouvementTypeID: 1,
    mouvementTypeDesignation: 'Entrée',
    certificationID: 1,
    certificationDesignation: 'Bio',
    sacTypeID: 1,
    sacTypeDesignation: 'Jute',
    objetEnStockID: 'LOT-001',
    objetEnStockType: 1,
    emplacementID: 1,
    emplacementDesignation: 'A1',
    siteID: 1,
    siteNom: 'Site Alpha',
    reference1: 'REF-001',
    reference2: 'REF-002',
    reference3: 'REF-003',
    dateMouvement: '2023-10-26T10:00:00Z',
    sens: 1,
    quantite: 100,
    poidsBrut: 1050.5,
    tareSacs: 50.5,
    tarePalettes: 0,
    poidsNetLivre: 1000,
    retentionPoids: 0,
    poidsNetAccepte: 1000,
    statut: 'Validé',
    commentaire: 'Première entrée de la saison',
    desactive: false,
    approbationUtilisateur: 'user1',
    approbationDate: '2023-10-26T11:00:00Z',
    creationUtilisateur: 'user1',
    creationDate: '2023-10-26T09:00:00Z',
    modificationUtilisateur: 'user1',
    modificationDate: '2023-10-26T09:00:00Z',
    rowVersionKey: null,
    produitID: 1,
  },
  {
    id: '2',
    magasinID: 2,
    magasinNom: 'Magasin B',
    campagneID: '2023',
    exportateurID: 102,
    exportateurNom: 'Exportateur Y',
    mouvementTypeID: 2,
    mouvementTypeDesignation: 'Sortie',
    certificationID: 2,
    certificationDesignation: 'Fair Trade',
    sacTypeID: 2,
    sacTypeDesignation: 'Plastique',
    objetEnStockID: 'LOT-002',
    objetEnStockType: 1,
    emplacementID: 2,
    emplacementDesignation: 'B2',
    siteID: 2,
    siteNom: 'Site Beta',
    reference1: 'REF-004',
    reference2: 'REF-005',
    reference3: 'REF-006',
    dateMouvement: '2023-10-27T14:00:00Z',
    sens: -1,
    quantite: 50,
    poidsBrut: 525.25,
    tareSacs: 25.25,
    tarePalettes: 0,
    poidsNetLivre: 500,
    retentionPoids: 0,
    poidsNetAccepte: 500,
    statut: 'Validé',
    commentaire: 'Sortie pour exportation',
    desactive: false,
    approbationUtilisateur: 'user2',
    approbationDate: '2023-10-27T15:00:00Z',
    creationUtilisateur: 'user2',
    creationDate: '2023-10-27T13:00:00Z',
    modificationUtilisateur: 'user2',
    modificationDate: '2023-10-27T13:00:00Z',
    rowVersionKey: null,
    produitID: 2,
  },
];
